### ISSUE TITLE
Unable to integrate this into iOS using Heroku

### ISSUE THREAD

**Issue by loxx123** [parse-server-modules/parse-server-firebase-auth-adapter#4]
I've added this to index.js in the var creation for parse server under  "var api = new ParseServer({...});"
```
"auth" : {
       "firebase" : {
           "module" : "parse-server-firebase-auth-adapter",
           "databaseURL" : "https://myserver.firebaseio.com/",
           "credential" : __dirname + '/firebase.json'
       }
  },
```

i've add two config variables to Heroku
```
FIREBASE_DATABASE_URL = https://myserver.firebaseio.com/
FIREBASE_SERVICE_ACCOUNT_KEY = firebase.json
```
i've added to package.json the following:
```
"dependencies": {
    "express": "~4.16.3",
    "kerberos": "~1.0.0",
    "parse": "~2.1.0",
    "parse-server": "parse-community/parse-server#master",
    "parse-server-firebase-auth-adapter": "~0.0.4"
  },
```
and in ios i've done this
```
[[PFUser logInWithAuthTypeInBackground:@"firebase"
                                          authData:@{@"id":authResult.user.uid, @"access_token" : self.incomingAuthString}] continueWithSuccessBlock:^id(BFTask *task) {
                
                PFUser * newUser = task.result;
                NSLog(@"new user %@", newUser);
                
                return nil;
                
            }];
```
the error i get in console is this

```
2018-09-30T14:40:29.636Z - Uncaught internal server error. { Error: Cannot find module 'firebase.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/app/node_modules/parse-server-firebase-auth-adapter/lib/index.js:23:39)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' } Error: Cannot find module '/firebase.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/app/node_modules/parse-server-firebase-auth-adapter/lib/index.js:23:39)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

```

error i get in ios is this
`[Error]: {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.17.1)
`

any help would be appreciated. i'm using parse server example, and i've uploaded the firebase.json file to my private repot in the main directory. it doesn't have it's own special folder, i've just added it to the main server example directory and i don't know if the config vars in Heroku are finding it. i've tried all combos for the config var from ../../firebase.json to ../firebase.json to /firebase.json to firebase.json and the same error to console is happening. 

thanks for your help

**Comment by loxx123** [comment]
i fixed this by adding ../../../firebase.json
